name: PBB Actions Workflow 

on: 
push:
pull_request: 
  types: [open, closed, assigned, reopened]

jobs:         
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: List Files
        run: |
           pwd
           ls -la
           echo $GITHUB_SHA
           echo $GITHUB_REPOSITORY
           echo $GITHUB_WORKSPACE
           echo "${{ github.token }}"
      - name: checkouts
        uses: actions/checkout@v1
      - name: List Files after
        run: |
           pwd
           ls -a
      - name: simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
           who-to-greet: amith
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"